chore(docs): README refactor
bee344/asset-hub-examples pull request #1
Opened 2024-03-04 13:16 UTC by bee344

2024-03-04 14:14 UTC, IkerAlus requested changes
First review done. I havent checked the examples. 

General structure and level of content is all good but we need to improve a couple of things.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +Foreign assets are those assets in Asset Hub whose native blockchain is not Asset Hub. These are mainly native tokens from other parachains or bridged tokens from other consensus systems (such as Eth
Add a paragraph above like:

"Assets, both native and foreign, are stored as a map from an ID to information about the asset, including a management team, total supply, total number of accounts, its sufficiency for account existence, and more. Additionally, the asset owner can register metadata like the name, symbol, and number of decimals for representation.

Some assets, as determined by on-chain governance, are regarded as “sufficient”. Sufficiency means that the asset balance is enough to create the account on-chain, with no need for the DOT existential deposit. Likewise, you cannot send a non-sufficient asset to an account that does not exist. Sufficient assets can be used to pay transaction fees (i.e. there is no need to hold DOT on the account). Assets do have a minimum balance, and if an account drops below that balance, the dust is lost. 

For an more details on general asset management in Asset Hub, refer to [the assets documentation](https://wiki.polkadot.network/docs/build-integrate-assets#assets-basics) of the Polkadot Wiki."

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +Practically speaking, foreign assets are handled by the `foreign-assets` pallet in Asset Hub, which is an instance of the previously mentioned `assets` pallet. Hence, this pallet exposes the same int
```suggestion
Practically speaking, foreign assets are handled by the `foreign-assets` pallet in Asset Hub, which is an instance of [the `assets` pallet](https://marketplace.substrate.io/pallets/pallet-assets/). Hence, this pallet exposes the same interface to users and other pallets as `assets` pallet. For example, to transfer a certain amount of a foreign asset (id) to an account (target), this pallet exposes the following call: 
```

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +The main functions you will probably interact with are `foreignAssets.transfer_allow_death` and `foreignAssets.transfer_keep_alive`. These functions transfer some `amount` (balance) of an `AssetId` (
```suggestion
The main functions you will probably interact with are `foreignAssets.transfer_allow_death` and `foreignAssets.transfer_keep_alive`.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +Note that you can use the same addresses (except [pure proxies](https://wiki.polkadot.network/docs/learn-proxies-pure#anonymous-proxy-pure-proxy)!) on the Asset Hub that
```suggestion
Note that you can use the same addresses (except [pure proxies](https://wiki.polkadot.network/docs/learn-proxies-pure#anonymous-proxy-pure-proxy)!) on Asset Hub that you use on the Relay Chain. The SS58 encodings are the same; only the chain information (genesis hash, etc.) will change on transaction construction.
```

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +you use on the Relay Chain. The SS58 encodings are the same; only the chain information (genesis hash, etc.) will change on transaction construction.
```suggestion
```

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> -### Running a Polkadot Asset Hub node
Line 90 of the new version is wrong, we are missing teleport to be mentioned:

Suggestion:

"Currently, foreign assets can be sent and received in the Asset Hub either with a [Reserve Backed Transfer or Teleporting](https://wiki.polkadot.network/docs/learn-xcm-pallet#transfer-reserve-vs-teleport) from other parachains. In both cases, the event emitted when processing the transfer is the `foreignAssets.issued` event. Hence, you should listen to these events, pointing to an address in their system. For this, you must query every new block created, loop through the events array, filter for any `foreignAssets.issued` event, and apply the appropriate business logic."

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> -
Line 97 is wrong, the relay chain is not queried.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> -
please double check that the info of lines 97 and 98 also applies for asset hub when receiving XMC.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> -Using the Asset Hub will require running a parachain node to sync the chain. This is very similar to running a Polkadot node, with the addition of some extra flags. You can download the latest releas
Line 105 of new version and other ocurrences: Do not mention system parachains, always talk about Asset Hub

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +Using the generic endpoints for the pallets, sidecar can also retrieve values specific to the configuration of the pallet, such as `constants`, `dispatchables`, `errors`, `events` and `storage`.
Line 139 above and other occurrences: let's call it Sidecar or API Sidecar. Not "the sidecar" etc.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +Using the generic endpoints for the pallets, sidecar can also retrieve values specific to the configuration of the pallet, such as `constants`, `dispatchables`, `errors`, `events` and `storage`.
I would remove Line 179 and everything below and add it to the PJS example, Here it is enough if we mention how to submit a transaction (already signed and ready, a byte array). You can reference the relevant example here.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +#### Tx Wrapper Polkadot
Remove this section and any txwrapper mention if there is no foreign assets support on time.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +#### Types of Nodes
dont we have any update about the potential different node functioning? like run a archive node for a  parachain with only a full node for relay and so on.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +NoS stands for Node + (API) Sidecar and consists of a simple script to launch a full node of [Asset Hub](https://wiki.polkadot.network/docs/learn-system-chains#asset-hub) together with an instance of
remove link to Asset Hub here.

2024-03-04 14:14 UTC, IkerAlus commented on README.md
> +#### Maintenance
we need to put more datails about monitoring runtime upgrades. As said in my doc, something like [this](https://wiki.polkadot.network/docs/learn-runtime-upgrades#monitoring-runtime-changes) (or just linking it adequately) for Asset Hub

2024-03-05 12:21 UTC, bee344 commented on README.md
> +Foreign assets are those assets in Asset Hub whose native blockchain is not Asset Hub. These are mainly native tokens from other parachains or bridged tokens from other consensus systems (such as Eth
Cool, at first that paragraph was in the guide but I was in doubt on whether we wanted the guide to be more or less constricted to just foreignAssets, so I removed it

2024-03-07 13:52 UTC, merged